import 'package:flutter/material.dart';
import 'package:gallerywidget/widget/subScreenWidget/subScreenAll.dart';

class DataWidget {
  Widget child;
  String sourceFilePath;
  String image;
  String title;
  String videoUrl;
  String url;
  DataWidget({this.child, this.sourceFilePath, this.image, this.title, this.videoUrl, this.url});
}

final dataWidgets = [
  DataWidget(
      child: AbsordPointerWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/absorbPointer/detailWidget.dart',
      image: "",
      title: "AbsorbPointer",
      videoUrl: "https://youtu.be/65HoWqBboI8",
      url: "https://api.flutter.dev/flutter/widgets/AbsorbPointer-class.html"),
  DataWidget(
      child: AlertDialogWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/alertDialog/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/material-alert-dialog.png",
      title: "AlertDialog",
      videoUrl: "https://youtu.be/75CsnyRXf5I",
      url: "https://api.flutter.dev/flutter/material/AlertDialog-class.html"),
  DataWidget(
      child: AlignWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/align/detailWidget.dart',
      image: "",
      title: "Align",
      videoUrl: "https://youtu.be/g2E7yl3MwMk",
      url: "https://api.flutter.dev/flutter/widgets/Align-class.html"),
  DataWidget(
      child: AnimatedBuilderWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/animatedBuilder/detailWidget.dart',
      image: "",
      title: "AnimatedBuilder",
      videoUrl: "https://youtu.be/N-RiyZlv8v8",
      url: "https://api.flutter.dev/flutter/widgets/AnimatedBuilder-class.html"),
  DataWidget(
      child: AnimatedContainerWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/animatedContainer/detailWidget.dart',
      image: "",
      title: "AnimatedContainer",
      videoUrl: "https://youtu.be/yI-8QHpGIP4",
      url: "https://api.flutter.dev/flutter/widgets/AnimatedContainer-class.html"),
  DataWidget(
      child: AnimatedCrossFadeWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/animatedCrossFade/detailWidget.dart',
      image: "",
      title: "AnimatedCrossFade",
      videoUrl: "https://youtu.be/PGK2UUAyE54",
      url: "https://api.flutter.dev/flutter/widgets/AnimatedCrossFade-class.html"),
  DataWidget(
      child: AnimatedDefaultTextStyleWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/animatedDefaultTextStyle/detailWidget.dart',
      image: "",
      title: "AnimatedDefaultTextStyle",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/AnimatedDefaultTextStyle-class.html"),
  DataWidget(
      child: AnimatedListWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/animatedList/detailWidget.dart',
      image: "",
      title: "AnimatedList",
      videoUrl: "https://youtu.be/ZtfItHwFlZ8",
      url: "https://api.flutter.dev/flutter/widgets/AnimatedList-class.html"),
  DataWidget(
      child: AnimatedModalBarrierWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/animatedModalBarrier/detailWidget.dart',
      image: "",
      title: "AnimatedModalBarrier",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/AnimatedModalBarrier-class.html"),
  DataWidget(
      child: AnimatedOpacityWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/animatedOpacity/detailWidget.dart',
      image: "",
      title: "AnimatedOpacity",
      videoUrl: "https://youtu.be/QZAvjqOqiLY",
      url: "https://api.flutter.dev/flutter/widgets/AnimatedOpacity-class.html"),
  DataWidget(
      child: AnimatedPhysicalModelWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/animatedPhysicalModel/detailWidget.dart',
      image: "",
      title: "AnimatedPhysicalModel",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/AnimatedPhysicalModel-class.html"),
  DataWidget(
      child: AnimatedPositionedWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/animatedPositioned/detailWidget.dart',
      image: "",
      title: "AnimatedPositioned",
      videoUrl: "https://youtu.be/hC3s2YdtWt8",
      url: "https://api.flutter.dev/flutter/widgets/AnimatedPositioned-class.html"),
  DataWidget(
      child: AnimatedSizeWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/animatedSize/detailWidget.dart',
      image: "",
      title: "AnimatedSize",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/AnimatedSize-class.html"),
  DataWidget(
      child: AnimatedWidgetWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/animatedWidget/detailWidget.dart',
      image: "",
      title: "AnimatedWidget",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/AnimatedWidget-class.html"),
  DataWidget(
      child: AnimatedWidgetBaseStateWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/animatedWidgetBaseState/detailWidget.dart',
      image: "",
      title: "AnimatedWidgetBaseState",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/AnimatedWidgetBaseState-class.html"),
  DataWidget(
      child: AppBarWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/appBar/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/material-app-bar.png",
      title: "AppBar",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/AppBar-class.html"),
  DataWidget(
      child: AspectRatioWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/aspectRatio/detailWidget.dart',
      image: "",
      title: "AspectRatio",
      videoUrl: "https://youtu.be/XcnP3_mO_Ms",
      url: "https://api.flutter.dev/flutter/widgets/AspectRatio-class.html"),
  DataWidget(
      child: AssetBundleWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/assetBundle/detailWidget.dart',
      image: "",
      title: "AssetBundle",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/services/AssetBundle-class.html"),
  DataWidget(
      child: BackdropFilterWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/backdropFilter/detailWidget.dart',
      image: "",
      title: "BackdropFilter",
      videoUrl: "https://youtu.be/dYRs7Q1vfYI",
      url: "https://api.flutter.dev/flutter/widgets/BackdropFilter-class.html"),
  DataWidget(
      child: BaselineWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/baseline/detailWidget.dart',
      image: "",
      title: "Baseline",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/Baseline-class.html"),
  DataWidget(
      child: BottomNavigationBarWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/bottomNavigationBar/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/material-bottom-navigation-bar.png",
      title: "BottomNavigationBar",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/BottomNavigationBar-class.html"),
  DataWidget(
      child: BottomSheetWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/bottomSheet/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/material-bottom-sheets.png",
      title: "BottomSheet",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/BottomSheet-class.html"),
  DataWidget(
      child: ButtonBarWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/buttonBar/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/material-button-bar.png",
      title: "ButtonBar",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/ButtonBar-class.html"),
  DataWidget(
      child: CardWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/card/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/material-card.png",
      title: "Card",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/Card-class.html"),
  DataWidget(
      child: CenterWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/center/detailWidget.dart',
      image: "",
      title: "Center",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/Center-class.html"),
  DataWidget(
      child: CheckboxWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/checkbox/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/material-checkbox.png",
      title: "Checkbox",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/Checkbox-class.html"),
  DataWidget(
      child: ChipWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/chip/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/material-chip.png",
      title: "Chip",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/Chip-class.html"),
  DataWidget(
      child: CircularProgressIndicatorWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/circularProgressIndicator/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/material-circular-progress-indicator.png",
      title: "CircularProgressIndicator",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/CircularProgressIndicator-class.html"),
  DataWidget(
      child: ClipOvalWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/clipOval/detailWidget.dart',
      image: "",
      title: "ClipOval",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/ClipOval-class.html"),
  DataWidget(
      child: ClipPathWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/clipPath/detailWidget.dart',
      image: "",
      title: "ClipPath",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/ClipPath-class.html"),
  DataWidget(
      child: ClipRectWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/clipRect/detailWidget.dart',
      image: "",
      title: "ClipRect",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/ClipRect-class.html"),
  DataWidget(
      child: ColumnWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/column/detailWidget.dart',
      image: "",
      title: "Column",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/Column-class.html"),
  DataWidget(
      child: ConstrainedBoxWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/constrainedBox/detailWidget.dart',
      image: "",
      title: "ConstrainedBox",
      videoUrl: "https://youtu.be/o2KveVr7adg",
      url: "https://api.flutter.dev/flutter/widgets/ConstrainedBox-class.html"),
  DataWidget(
      child: ContainerWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/container/detailWidget.dart',
      image: "",
      title: "Container",
      videoUrl: "https://youtu.be/o2KveVr7adg",
      url: "https://api.flutter.dev/flutter/widgets/Container-class.html"),
  DataWidget(
      child: CupertinoActionSheetWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/cupertinoActionSheet/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/cupertino-action-sheet.png",
      title: "CupertinoActionSheet",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/cupertino/CupertinoActionSheet-class.html"),
  DataWidget(
      child: CupertinoActivityIndicatorWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/cupertinoActivityIndicator/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/cupertino-activity-indicator.png",
      title: "CupertinoActivityIndicator",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/cupertino/CupertinoActivityIndicator-class.html"),
  DataWidget(
      child: CupertinoAlertDialogWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/cupertinoAlertDialog/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/cupertino-alert-dialog.png",
      title: "CupertinoAlertDialog",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/cupertino/CupertinoAlertDialog-class.html"),
  DataWidget(
      child: CupertinoButtonWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/cupertinoButton/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/cupertino-button.png",
      title: "CupertinoButton",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/cupertino/CupertinoButton-class.html"),
  DataWidget(
      child: CupertinoContextMenuWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/cupertinoContextMenu/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/cupertino-context-menu.png",
      title: "CupertinoContextMenu",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/cupertino/CupertinoContextMenu-class.html"),
  DataWidget(
      child: CupertinoDatePickerWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/cupertinoDatePicker/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/cupertino-date-picker.png",
      title: "CupertinoDatePicker",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/cupertino/CupertinoDatePicker-class.html"),
  DataWidget(
      child: CupertinoDialogWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/cupertinoDialog/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/cupertino-dialog.png",
      title: "CupertinoDialog",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/cupertino/CupertinoDialog-class.html"),
  DataWidget(
      child: CupertinoDialogActionWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/cupertinoDialogAction/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/cupertino-dialog-action.png",
      title: "CupertinoDialogAction",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/cupertino/CupertinoDialogAction-class.html"),
  DataWidget(
      child: CupertinoFullscreenDialogTransitionWidgetScreen(),
      sourceFilePath:
          'lib/widget/subScreenWidget/cupertinoFullscreenDialogTransition/detailWidget.dart',
      image: "",
      title: "CupertinoFullscreenDialogTransition",
      videoUrl: "",
      url:
          "https://api.flutter.dev/flutter/cupertino/CupertinoFullscreenDialogTransition-class.html"),
  DataWidget(
      child: CupertinoNavigationBarWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/cupertinoNavigationBar/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/cupertino-nav-bar.png",
      title: "CupertinoNavigationBar",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/cupertino/CupertinoNavigationBar-class.html"),
  DataWidget(
      child: CupertinoPageScaffoldWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/cupertinoPageScaffold/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/cupertino-page-scaffold.png",
      title: "CupertinoPageScaffold",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/cupertino/CupertinoPageScaffold-class.html"),
  DataWidget(
      child: CupertinoPageTransitionWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/cupertinoPageTransition/detailWidget.dart',
      image: "",
      title: "CupertinoPageTransition",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/cupertino/CupertinoPageTransition-class.html"),
  DataWidget(
      child: CupertinoPickerWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/cupertinoPicker/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/cupertino-picker.png",
      title: "CupertinoPicker",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/cupertino/CupertinoPicker-class.html"),
  DataWidget(
      child: CupertinoPopupSurfaceWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/cupertinoPopupSurface/detailWidget.dart',
      image: "",
      title: "CupertinoPopupSurface",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/cupertino/CupertinoPopupSurface-class.html"),
  DataWidget(
      child: CupertinoScrollbarWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/cupertinoScrollbar/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/cupertino-scrollbar.png",
      title: "CupertinoScrollbar",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/cupertino/CupertinoScrollbar-class.html"),
  DataWidget(
      child: CupertinoSegmentedControlWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/cupertinoSegmentedControl/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/cupertino-segmented-control.png",
      title: "CupertinoSegmentedControl",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/cupertino/CupertinoSegmentedControl-class.html"),
  DataWidget(
      child: CupertinoSliderWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/cupertinoSlider/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/cupertino-slider.png",
      title: "CupertinoSlider",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/cupertino/CupertinoSlider-class.html"),
  DataWidget(
      child: CupertinoSlidingSegmentedControlWidgetScreen(),
      sourceFilePath:
          'lib/widget/subScreenWidget/cupertinoSlidingSegmentedControl/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/cupertino-sliding-segmented-control.png",
      title: "CupertinoSlidingSegmentedControl",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/cupertino/CupertinoSlidingSegmentedControl-class.html"),
  DataWidget(
      child: CupertinoSwitchWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/cupertinoSwitch/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/cupertino-switch.png",
      title: "CupertinoSwitch",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/cupertino/CupertinoSwitch-class.html"),
  DataWidget(
      child: CupertinoTabBarWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/cupertinoTabBar/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/cupertino-tab-bar.png",
      title: "CupertinoTabBar",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/cupertino/CupertinoTabBar-class.html"),
  DataWidget(
      child: CupertinoTabScaffoldWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/cupertinoTabScaffold/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/cupertino-tab-scaffold.png",
      title: "CupertinoTabScaffold",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/cupertino/CupertinoTabScaffold-class.html"),
  DataWidget(
      child: CupertinoTabViewWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/cupertinoTabView/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/cupertino-tab-view.png",
      title: "CupertinoTabView",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/cupertino/CupertinoTabView-class.html"),
  DataWidget(
      child: CupertinoTextFieldWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/cupertinoTextField/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/cupertino-textfield.png",
      title: "CupertinoTextField",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/cupertino/CupertinoTextField-class.html"),
  DataWidget(
      child: CupertinoTimerPickerWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/cupertinoTimerPicker/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/cupertino-timer-picker.png",
      title: "CupertinoTimerPicker",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/cupertino/CupertinoTimerPicker-class.html"),
  DataWidget(
      child: CustomMultiChildLayoutWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/customMultiChildLayout/detailWidget.dart',
      image: "",
      title: "CustomMultiChildLayout",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/CustomMultiChildLayout-class.html"),
  DataWidget(
      child: CustomPaintWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/customPaint/detailWidget.dart',
      image: "",
      title: "CustomPaint",
      videoUrl: "https://youtu.be/kp14Y4uHpHs",
      url: "https://api.flutter.dev/flutter/widgets/CustomPaint-class.html"),
  DataWidget(
      child: CustomScrollViewWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/customScrollView/detailWidget.dart',
      image: "",
      title: "CustomScrollView",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/CustomScrollView-class.html"),
  DataWidget(
      child: CustomSingleChildLayoutWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/customSingleChildLayout/detailWidget.dart',
      image: "",
      title: "CustomSingleChildLayout",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/CustomSingleChildLayout-class.html"),
  DataWidget(
      child: DataTableWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/dataTable/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/material-data-table.png",
      title: "DataTable",
      videoUrl: "https://youtu.be/ktTajqbhIcY",
      url: "https://api.flutter.dev/flutter/material/DataTable-class.html"),
  DataWidget(
      child: DateTimePickersWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/dateTimePickers/detailWidget.dart',
      image:
          "https://material-design.storage.googleapis.com/publish/material_v_9/0B7WCemMG6e0VY2h4WElGdEhPb2c/components_pickers.png",
      title: "DateTimePickers",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/showDatePicker.html"),
  DataWidget(
      child: DecoratedBoxWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/decoratedBox/detailWidget.dart',
      image: "",
      title: "DecoratedBox",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/DecoratedBox-class.html"),
  DataWidget(
      child: DecoratedBoxTransitionWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/decoratedBoxTransition/detailWidget.dart',
      image: "",
      title: "DecoratedBoxTransition",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/DecoratedBoxTransition-class.html"),
  DataWidget(
      child: DefaultTextStyleWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/defaultTextStyle/detailWidget.dart',
      image: "",
      title: "DefaultTextStyle",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/DefaultTextStyle-class.html"),
  DataWidget(
      child: DismissibleWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/dismissible/detailWidget.dart',
      image: "",
      title: "Dismissible",
      videoUrl: "https://youtu.be/iEMgjrfuc58",
      url: "https://api.flutter.dev/flutter/widgets/Dismissible-class.html"),
  DataWidget(
      child: DividerWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/divider/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/material-divider.png",
      title: "Divider",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/Divider-class.html"),
  DataWidget(
      child: DragTargetWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/dragTarget/detailWidget.dart',
      image: "",
      title: "DragTarget",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/DragTarget-class.html"),
  DataWidget(
      child: DraggableWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/draggable/detailWidget.dart',
      image: "",
      title: "Draggable",
      videoUrl: "https://youtu.be/QzA4c4QHZCY",
      url: "https://api.flutter.dev/flutter/widgets/Draggable-class.html"),
  DataWidget(
      child: DrawerWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/drawer/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/material-drawer.png",
      title: "Drawer",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/Drawer-class.html"),
  DataWidget(
      child: DropdownButtonWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/dropdownButton/detailWidget.dart',
      image:
          "https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B7WCemMG6e0VakJ6a0F2MFJaaDQ/components_menus.png",
      title: "DropdownButton",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/DropdownButton-class.html"),
  DataWidget(
      child: ExcludeSemanticsWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/excludeSemantics/detailWidget.dart',
      image: "",
      title: "ExcludeSemantics",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/ExcludeSemantics-class.html"),
  DataWidget(
      child: ExpandedWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/expanded/detailWidget.dart',
      image: "",
      title: "Expanded",
      videoUrl: "https://youtu.be/_rnZaagadyo",
      url: "https://api.flutter.dev/flutter/widgets/Expanded-class.html"),
  DataWidget(
      child: ExpansionPanelWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/expansionPanel/detailWidget.dart',
      image:
          "https://material-design.storage.googleapis.com/publish/material_v_9/0B7WCemMG6e0VOXF3eEJ3azZMSjg/components_expansion_panels.png",
      title: "ExpansionPanel",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/ExpansionPanel-class.html"),
  DataWidget(
      child: FadeTransitionWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/fadeTransition/detailWidget.dart',
      image: "",
      title: "FadeTransition",
      videoUrl: "https://youtu.be/rLwWVbv3xDQ",
      url: "https://api.flutter.dev/flutter/widgets/FadeTransition-class.html"),
  DataWidget(
      child: FittedBoxWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/fittedBox/detailWidget.dart',
      image: "",
      title: "FittedBox",
      videoUrl: "https://youtu.be/T4Uehk3_wlY",
      url: "https://api.flutter.dev/flutter/widgets/FittedBox-class.html"),
  DataWidget(
      child: FlatButtonWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/flatButton/detailWidget.dart',
      image:
          "https://material-design.storage.googleapis.com/publish/material_v_9/0B7WCemMG6e0VNDg3V3ZjU2hsNGc/components_buttons_usage3.png",
      title: "FlatButton",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/FlatButton-class.html"),
  DataWidget(
      child: FloatingActionButtonWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/floatingActionButton/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/material-floating-action-button.png",
      title: "FloatingActionButton",
      videoUrl: "https://youtu.be/2uaoEDOgk_I",
      url: "https://api.flutter.dev/flutter/material/FloatingActionButton-class.html"),
  DataWidget(
      child: FlowWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/flow/detailWidget.dart',
      image: "",
      title: "Flow",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/Flow-class.html"),
  DataWidget(
      child: FlutterLogoWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/flutterLogo/detailWidget.dart',
      image: "",
      title: "FlutterLogo",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/FlutterLogo-class.html"),
  DataWidget(
      child: FormWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/form/detailWidget.dart',
      image: "",
      title: "Form",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/Form-class.html"),
  DataWidget(
      child: FormFieldWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/formField/detailWidget.dart',
      image: "",
      title: "FormField",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/FormField-class.html"),
  DataWidget(
      child: FractionalTranslationWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/fractionalTranslation/detailWidget.dart',
      image: "",
      title: "FractionalTranslation",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/FractionalTranslation-class.html"),
  DataWidget(
      child: FractionallySizedBoxWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/fractionallySizedBox/detailWidget.dart',
      image: "",
      title: "FractionallySizedBox",
      videoUrl: "https://youtu.be/PEsY654EGZ0",
      url: "https://api.flutter.dev/flutter/widgets/FractionallySizedBox-class.html"),
  DataWidget(
      child: FutureBuilderWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/futureBuilder/detailWidget.dart',
      image: "",
      title: "FutureBuilder",
      videoUrl: "https://youtu.be/ek8ZPdWj4Qo",
      url: "https://api.flutter.dev/flutter/widgets/FutureBuilder-class.html"),
  DataWidget(
      child: GestureDetectorWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/gestureDetector/detailWidget.dart',
      image: "",
      title: "GestureDetector",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/GestureDetector-class.html"),
  DataWidget(
      child: GridViewWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/gridView/detailWidget.dart',
      image:
          "https://material-design.storage.googleapis.com/publish/material_v_9/0B7WCemMG6e0VandQYXpNMG9aQUk/components_grid_lists.png",
      title: "GridView",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/GridView-class.html"),
  DataWidget(
      child: HeroWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/hero/detailWidget.dart',
      image: "",
      title: "Hero",
      videoUrl: "https://youtu.be/Be9UH1kXFDw",
      url: "https://api.flutter.dev/flutter/widgets/Hero-class.html"),
  DataWidget(
      child: IconWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/icon/detailWidget.dart',
      image: "https://flutter.github.io/assets-for-api-docs/assets/widgets/icon.png",
      title: "Icon",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/Icon-class.html"),
  DataWidget(
      child: IconButtonWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/iconButton/detailWidget.dart',
      image:
          "https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B_udO5B8pzrzdXVuTlBoOTBjcU0/components_buttons_other1.png",
      title: "IconButton",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/IconButton-class.html"),
  DataWidget(
      child: IgnorePointerWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/ignorePointer/detailWidget.dart',
      image: "",
      title: "IgnorePointer",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/IgnorePointer-class.html"),
  DataWidget(
      child: ImageWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/image/detailWidget.dart',
      image: "https://flutter.dev/images/owl.jpg",
      title: "Image",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/Image-class.html"),
  DataWidget(
      child: IndexedStackWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/indexedStack/detailWidget.dart',
      image: "",
      title: "IndexedStack",
      videoUrl: "https://youtu.be/_O0PPD1Xfbk",
      url: "https://api.flutter.dev/flutter/widgets/IndexedStack-class.html"),
  DataWidget(
      child: IntrinsicHeightWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/intrinsicHeight/detailWidget.dart',
      image: "",
      title: "IntrinsicHeight",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/IntrinsicHeight-class.html"),
  DataWidget(
      child: IntrinsicWidthWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/intrinsicWidth/detailWidget.dart',
      image: "",
      title: "IntrinsicWidth",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/IntrinsicWidth-class.html"),
  DataWidget(
      child: LayoutBuilderWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/layoutBuilder/detailWidget.dart',
      image: "",
      title: "LayoutBuilder",
      videoUrl: "https://youtu.be/IYDVcriKjsw",
      url: "https://api.flutter.dev/flutter/widgets/LayoutBuilder-class.html"),
  DataWidget(
      child: LimitedBoxWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/limitedBox/detailWidget.dart',
      image: "",
      title: "LimitedBox",
      videoUrl: "https://youtu.be/uVki2CIzBTs",
      url: "https://api.flutter.dev/flutter/widgets/LimitedBox-class.html"),
  DataWidget(
      child: LinearProgressIndicatorWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/linearProgressIndicator/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/material-linear-progress-indicator.png",
      title: "LinearProgressIndicator",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/LinearProgressIndicator-class.html"),
  DataWidget(
      child: ListBodyWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/listBody/detailWidget.dart',
      image: "",
      title: "ListBody",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/ListBody-class.html"),
  DataWidget(
      child: ListTileWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/listTile/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/material-list-tile.png",
      title: "ListTile",
      videoUrl: "https://youtu.be/l8dj0yPBvgQ",
      url: "https://api.flutter.dev/flutter/material/ListTile-class.html"),
  DataWidget(
      child: ListViewWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/listView/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/material-list-tile.png",
      title: "ListView",
      videoUrl: "https://youtu.be/KJpkjHGiI5A",
      url: "https://api.flutter.dev/flutter/widgets/ListView-class.html"),
  DataWidget(
      child: LongPressDraggableWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/longPressDraggable/detailWidget.dart',
      image: "",
      title: "LongPressDraggable",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/LongPressDraggable-class.html"),
  DataWidget(
      child: MaterialAppWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/materialApp/detailWidget.dart',
      image:
          "https://storage.googleapis.com/material-design/publish/material_v_11/assets/0Bx4BSt6jniD7Y1huOXVQdlFPMmM/materialdesign_introduction.png",
      title: "MaterialApp",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/MaterialApp-class.html"),
  DataWidget(
      child: MediaQueryWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/mediaQuery/detailWidget.dart',
      image: "",
      title: "MediaQuery",
      videoUrl: "https://youtu.be/A3WrA4zAaPw",
      url: "https://api.flutter.dev/flutter/widgets/MediaQuery-class.html"),
  DataWidget(
      child: MergeSemanticsWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/mergeSemantics/detailWidget.dart',
      image: "",
      title: "MergeSemantics",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/MergeSemantics-class.html"),
  DataWidget(
      child: NavigatorWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/navigator/detailWidget.dart',
      image: "",
      title: "Navigator",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/Navigator-class.html"),
  DataWidget(
      child: NestedScrollViewWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/nestedScrollView/detailWidget.dart',
      image: "",
      title: "NestedScrollView",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/NestedScrollView-class.html"),
  DataWidget(
      child: NotificationListenerWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/notificationListener/detailWidget.dart',
      image: "",
      title: "NotificationListener",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/NotificationListener-class.html"),
  DataWidget(
      child: OffstageWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/offstage/detailWidget.dart',
      image: "",
      title: "Offstage",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/Offstage-class.html"),
  DataWidget(
      child: OpacityWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/opacity/detailWidget.dart',
      image: "",
      title: "Opacity",
      videoUrl: "https://youtu.be/9hltevOHQBw",
      url: "https://api.flutter.dev/flutter/widgets/Opacity-class.html"),
  DataWidget(
      child: OutlineButtonWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/outlineButton/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/material-outline-button.png",
      title: "OutlineButton",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/OutlineButton-class.html"),
  DataWidget(
      child: OverflowBoxWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/overflowBox/detailWidget.dart',
      image: "",
      title: "OverflowBox",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/OverflowBox-class.html"),
  DataWidget(
      child: PaddingWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/padding/detailWidget.dart',
      image: "",
      title: "Padding",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/Padding-class.html"),
  DataWidget(
      child: PageViewWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/pageView/detailWidget.dart',
      image: "",
      title: "PageView",
      videoUrl: "https://youtu.be/J1gE9xvph-A",
      url: "https://api.flutter.dev/flutter/widgets/PageView-class.html"),
  DataWidget(
      child: PlaceholderWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/placeholder/detailWidget.dart',
      image: "",
      title: "Placeholder",
      videoUrl: "https://youtu.be/LPe56fezmoo",
      url: "https://api.flutter.dev/flutter/widgets/Placeholder-class.html"),
  DataWidget(
      child: PopupMenuButtonWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/popupMenuButton/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/material-popup-menu-button.png",
      title: "PopupMenuButton",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/PopupMenuButton-class.html"),
  DataWidget(
      child: PositionedTransitionWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/positionedTransition/detailWidget.dart',
      image: "",
      title: "PositionedTransition",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/PositionedTransition-class.html"),
  DataWidget(
      child: RadioWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/radio/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/material-radio.png",
      title: "Radio",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/Radio-class.html"),
  DataWidget(
      child: RaisedButtonWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/raisedButton/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/material-raised-button.png",
      title: "RaisedButton",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/RaisedButton-class.html"),
  DataWidget(
      child: RawImageWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/rawImage/detailWidget.dart',
      image: "",
      title: "RawImage",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/RawImage-class.html"),
  DataWidget(
      child: RawKeyboardListenerWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/rawKeyboardListener/detailWidget.dart',
      image: "",
      title: "RawKeyboardListener",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/RawKeyboardListener-class.html"),
  DataWidget(
      child: RefreshIndicatorWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/refreshIndicator/detailWidget.dart',
      image:
          "https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B7WCemMG6e0VS2kzSmZwNnNKQVk/patterns-swipe-to-refresh.png",
      title: "RefreshIndicator",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/RefreshIndicator-class.html"),
  DataWidget(
      child: RichTextWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/richText/detailWidget.dart',
      image: "",
      title: "RichText",
      videoUrl: "https://youtu.be/rykDVh-QFfw",
      url: "https://api.flutter.dev/flutter/widgets/RichText-class.html"),
  DataWidget(
      child: RotatedBoxWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/rotatedBox/detailWidget.dart',
      image: "",
      title: "RotatedBox",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/RotatedBox-class.html"),
  DataWidget(
      child: RotationTransitionWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/rotationTransition/detailWidget.dart',
      image: "",
      title: "RotationTransition",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/RotationTransition-class.html"),
  DataWidget(
      child: RowWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/row/detailWidget.dart',
      image: "",
      title: "Row",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/Row-class.html"),
  DataWidget(
      child: ScaffoldWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/scaffold/detailWidget.dart',
      image:
          "https://storage.googleapis.com/material-design/publish/material_v_11/assets/0Bx4BSt6jniD7T0hfM01sSmRyTG8/layout_structure_regions_mobile.png",
      title: "Scaffold",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/Scaffold-class.html"),
  DataWidget(
      child: ScaleTransitionWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/scaleTransition/detailWidget.dart',
      image: "",
      title: "ScaleTransition",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/ScaleTransition-class.html"),
  DataWidget(
      child: ScrollConfigurationWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/scrollConfiguration/detailWidget.dart',
      image: "",
      title: "ScrollConfiguration",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/ScrollConfiguration-class.html"),
  DataWidget(
      child: ScrollableWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/scrollable/detailWidget.dart',
      image: "",
      title: "Scrollable",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/Scrollable-class.html"),
  DataWidget(
      child: ScrollbarWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/scrollbar/detailWidget.dart',
      image: "",
      title: "Scrollbar",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/Scrollbar-class.html"),
  DataWidget(
      child: SemanticsWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/semantics/detailWidget.dart',
      image: "",
      title: "Semantics",
      videoUrl: "https://youtu.be/NvtMt_DtFrQ",
      url: "https://api.flutter.dev/flutter/widgets/Semantics-class.html"),
  DataWidget(
      child: SimpleDialogWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/simpleDialog/detailWidget.dart',
      image:
          "https://material-design.storage.googleapis.com/publish/material_v_9/0B7WCemMG6e0VVGNnN3NvMGdoQTg/components_dialogs.png",
      title: "SimpleDialog",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/SimpleDialog-class.html"),
  DataWidget(
      child: SingleChildScrollViewWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/singleChildScrollView/detailWidget.dart',
      image: "",
      title: "SingleChildScrollView",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/SingleChildScrollView-class.html"),
  DataWidget(
      child: SizeTransitionWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/sizeTransition/detailWidget.dart',
      image: "",
      title: "SizeTransition",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/SizeTransition-class.html"),
  DataWidget(
      child: SizedBoxWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/sizedBox/detailWidget.dart',
      image: "",
      title: "SizedBox",
      videoUrl: "https://youtu.be/EHPu_DzRfqA",
      url: "https://api.flutter.dev/flutter/widgets/SizedBox-class.html"),
  DataWidget(
      child: SizedOverflowBoxWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/sizedOverflowBox/detailWidget.dart',
      image: "",
      title: "SizedOverflowBox",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/SizedOverflowBox-class.html"),
  DataWidget(
      child: SlideTransitionWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/slideTransition/detailWidget.dart',
      image: "",
      title: "SlideTransition",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/SlideTransition-class.html"),
  DataWidget(
      child: SlideWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/slider/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/material-slider.png",
      title: "Slider",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/Slider-class.html"),
  DataWidget(
      child: SliverAppBarWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/sliverAppBar/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/material-app-bar.png",
      title: "SliverAppBar",
      videoUrl: "https://youtu.be/R9C5KMJKluE",
      url: "https://api.flutter.dev/flutter/material/SliverAppBar-class.html"),
  DataWidget(
      child: SnackBarWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/snackBar/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/material-snack-bar.png",
      title: "SnackBar",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/SnackBar-class.html"),
  DataWidget(
      child: StackWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/stack/detailWidget.dart',
      image: "",
      title: "Stack",
      videoUrl: "https://youtu.be/liEGSeD3Zt8",
      url: "https://api.flutter.dev/flutter/widgets/Stack-class.html"),
  DataWidget(
      child: StepperWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/stepper/detailWidget.dart',
      image:
          "https://material-design.storage.googleapis.com/publish/material_v_9/0B7WCemMG6e0VTndyUnNCR2tQREE/components_steppers.png",
      title: "Stepper",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/Stepper-class.html"),
  DataWidget(
      child: StreamBuilderWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/streamBuilder/detailWidget.dart',
      image: "",
      title: "StreamBuilder",
      videoUrl: "https://youtu.be/MkKEWHfy99Y",
      url: "https://api.flutter.dev/flutter/widgets/StreamBuilder-class.html"),
  DataWidget(
      child: SwitchWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/switch/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/material-switch.png",
      title: "Switch",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/Switch-class.html"),
  DataWidget(
      child: TabBarWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/tabBar/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/material-tab-bar.png",
      title: "TabBar",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/TabBar-class.html"),
  DataWidget(
      child: TabBarViewWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/tabBarView/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/material-tab-bar.png",
      title: "TabBarView",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/TabBarView-class.html"),
  DataWidget(
      child: TableWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/tabBarView/detailWidget.dart',
      image: "",
      title: "Table",
      videoUrl: "https://youtu.be/_lbE0wsVZSw",
      url: "https://api.flutter.dev/flutter/widgets/Table-class.html"),
  DataWidget(
      child: TextWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/text/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/material-text-field.png",
      title: "Text",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/Text-class.html"),
  DataWidget(
      child: TextFieldWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/textField/detailWidget.dart',
      image: "",
      title: "TextField",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/TextField-class.html"),
  DataWidget(
      child: ThemeWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/theme/detailWidget.dart',
      image: "",
      title: "Theme",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/material/Theme-class.html"),
  DataWidget(
      child: TooltipWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/tooltip/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/material-tooltip.png",
      title: "Tooltip",
      videoUrl: "https://youtu.be/EeEfD5fI-5Q",
      url: "https://api.flutter.dev/flutter/material/Tooltip-class.html"),
  DataWidget(
      child: TransformWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/transform/detailWidget.dart',
      image: "",
      title: "Transform",
      videoUrl: "https://youtu.be/9z_YNlRlWfA",
      url: "https://api.flutter.dev/flutter/widgets/Transform-class.html"),
  DataWidget(
      child: WidgetsAppWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/widgetsApp/detailWidget.dart',
      image: "https://flutter.dev/images/widget-catalog/material-widgets-app.png",
      title: "WidgetsApp",
      videoUrl: "",
      url: "https://api.flutter.dev/flutter/widgets/WidgetsApp-class.html"),
  DataWidget(
      child: WrapWidgetScreen(),
      sourceFilePath: 'lib/widget/subScreenWidget/wrap/detailWidget.dart',
      image: "",
      title: "Wrap",
      videoUrl: "https://youtu.be/z5iw2SeFx2M",
      url: "https://api.flutter.dev/flutter/widgets/Wrap-class.html"),
];
